deploy & deployment update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,14 +52,14 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: env-vars
-          path: .
+          path: env-artifact
 
       - name: Check if env-vars.env was downloaded
-        run: test -f env-vars.env || (echo "Missing env-vars.env file. Previous job likely failed." && exit 1)
+        run: test -f env-artifact/env-vars.env || (echo "Missing env-vars.env file. Previous job likely failed." && exit 1)
 
       - name: Export .env to GITHUB_ENV
         run: |
-          cat env-vars.env >> $GITHUB_ENV
+          cat env-artifact/env-vars.env >> $GITHUB_ENV
 
       - name: Configure kubeconfig for EKS cluster
         run: |
