deploy & deployment update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,9 +54,12 @@ jobs:
           name: env-vars
           path: .
 
+      - name: Check if env-vars.env was downloaded
+        run: test -f env-vars.env || (echo "Missing env-vars.env file. Previous job likely failed." && exit 1)
+
       - name: Export .env to GITHUB_ENV
         run: |
-          cat .env >> $GITHUB_ENV
+          cat env-vars.env >> $GITHUB_ENV
 
       - name: Configure kubeconfig for EKS cluster
         run: |
